# Generated by Django 4.1.1 on 2022-09-27 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_users_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='date_created',
        ),
    ]
