# Generated by Django 4.1.1 on 2022-09-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_remove_users_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
